// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ImageDisplayer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidImageDisplayerPackageString = "cfd2f0a6-24d9-4998-9e71-91bcd4f291cf";
        public static Guid guidImageDisplayerPackage = new Guid(guidImageDisplayerPackageString);

        public const string guidImageDisplayerPackageCmdSetString = "e08427b5-7453-4f3e-83cb-1d41d7d71370";
        public static Guid guidImageDisplayerPackageCmdSet = new Guid(guidImageDisplayerPackageCmdSetString);

        public const string MyImagesString = "92faab66-5cb5-4901-88c5-90181f124951";
        public static Guid MyImages = new Guid(MyImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FirstCommandId = 0x0100;
        public const int cmdidMyWindowCommand = 0x1021;
        public const int cmdidImageDisplayWindowCommand = 0x1022;
        public const int window = 0x0001;
    }
}