// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ImageDisplayer
{
    internal sealed partial class Vsix
    {
        public const string Id = "8864c6b6-57eb-408e-9507-33e1debf80be";
        public const string Name = "ImageDisplayer";
        public const string Description = @"This extension display your selected static (jpg, png,...) image or animated image (gif).This exteThis app ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Valentinas Kaminskas (valentk777)";
        public const string Tags = "";
    }
}
